# Generated by Django 3.2.9 on 2021-11-30 17:30

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211130_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_update',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meta_description',
            field=models.TextField(help_text='حداکثر 170 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(170)], verbose_name='meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meta_title',
            field=models.CharField(help_text='حداکثر 60 کاراکتر', max_length=60, null=True, verbose_name='meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.posts_thumb_path),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(help_text='حداکثر 170 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(170)], verbose_name='meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(help_text='حداکثر 60 کاراکتر', max_length=60, null=True, verbose_name='meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
