# Generated by Django 3.2.9 on 2021-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211130_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='meta_title',
        ),
    ]
