# Generated by Django 3.2.9 on 2022-01-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211130_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language_field',
            field=models.CharField(blank=True, choices=[('persian', 'persian'), ('english', 'english')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='language_field',
            field=models.CharField(blank=True, choices=[('persian', 'persian'), ('english', 'english')], max_length=256, null=True),
        ),
    ]
