# Generated by Django 3.2.9 on 2021-12-01 19:54

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer', models.CharField(blank=True, max_length=50, null=True)),
                ('time_of_issue', models.DateField(blank=True, null=True)),
                ('expired_time', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles)),
                ('link_cert', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_text', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_link', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_text', models.CharField(blank=True, max_length=50, null=True)),
                ('btn_link', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('percent', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
