# Generated by Django 3.2.9 on 2021-12-02 21:34

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20211201_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='videocv',
            new_name='video_cv',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='settings',
            name='meta_description',
            field=models.TextField(help_text='حداکثر 170 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(170)], verbose_name='meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='meta_title',
            field=models.CharField(help_text='حداکثر 60 کاراکتر', max_length=60, null=True, verbose_name='meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='video_cv_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles),
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('meta_title', models.CharField(help_text='حداکثر 60 کاراکتر', max_length=60, null=True, verbose_name='meta title (SEO)')),
                ('meta_description', models.TextField(help_text='حداکثر 170 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(170)], verbose_name='meta description (SEO)')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order'],
            },
        ),
    ]
