# Generated by Django 3.2.9 on 2022-01-08 16:51

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20220106_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('language_field', models.CharField(blank=True, choices=[('persian', 'persian'), ('english', 'english')], max_length=256, null=True, verbose_name='زبان این محتوا')),
                ('slug', models.CharField(max_length=60, null=True, verbose_name='پیوند یکتا')),
                ('meta_title', models.CharField(help_text='حداکثر 60 کاراکتر', max_length=60, null=True, verbose_name='meta title (SEO)')),
                ('meta_description', models.TextField(help_text='حداکثر 170 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(170)], verbose_name='meta description (SEO)')),
                ('env_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enviorment Name')),
                ('name_of_site', models.CharField(blank=True, default='علی اسمعیلی', max_length=50, null=True, verbose_name='Site Name')),
                ('slang', models.CharField(blank=True, default='برنامه نویس و تولید کننده محتوا', max_length=50, null=True, verbose_name='Slang of your site')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content Of the Hero Section')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles, verbose_name='Avatar Image')),
                ('cv', models.FileField(blank=True, null=True, upload_to=main.models.Homefiles, verbose_name='Your CV File')),
                ('info_title1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Information Title 1')),
                ('info_content1', models.TextField(blank=True, null=True, verbose_name='Information Content 1')),
                ('info_title2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Information Title 2')),
                ('info_content2', models.TextField(blank=True, null=True, verbose_name='Information Content 2')),
                ('info_title3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Information Title 3')),
                ('info_content3', models.TextField(blank=True, null=True, verbose_name='Information Content 3')),
                ('info_title4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Information Title 4')),
                ('info_content4', models.TextField(blank=True, null=True, verbose_name='Information Content 4')),
                ('customers_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customers Title')),
                ('customers_num', models.IntegerField(blank=True, null=True, verbose_name='Customers Number')),
                ('years_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Experience Years')),
                ('years_num', models.IntegerField(blank=True, null=True, verbose_name='Experience Years Number')),
                ('certificates_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Certificate Title')),
                ('certificates_num', models.IntegerField(blank=True, null=True, verbose_name='Certificate Numbers')),
                ('tea_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tea Title')),
                ('tea_num', models.IntegerField(blank=True, null=True, verbose_name='Tea Numbers')),
                ('video_cv', models.URLField(blank=True, null=True, verbose_name='Video CV Link')),
                ('video_cv_image', models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles, verbose_name='Video CV Image')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': ' Settings',
            },
        ),
        migrations.DeleteModel(
            name='settings',
        ),
        migrations.AlterField(
            model_name='certificates',
            name='expired_time',
            field=models.DateField(blank=True, null=True, verbose_name='Time Of Expiration'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='issuer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Institute'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='link_cert',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='Link Of Certificate'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles, verbose_name='Logo Of Institute'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name Of Certificate'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='time_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Time of Issue'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email of User'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name Of User'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject Of message'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='btn_link',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='btn_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Title'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of institute'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Institute location'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Years of Education'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='btn_link',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='btn_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Title'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Company'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company location'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content of Page'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Homefiles, verbose_name='Thumbnail of page'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name of Page'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of page'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Skill'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='percent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Percentage of Skill Experience'),
        ),
    ]
