# Generated by Django 3.2.9 on 2021-12-01 20:52

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('meta_title', models.CharField(help_text='حداکثر 60 کاراکتر', max_length=60, null=True, verbose_name='meta title (SEO)')),
                ('meta_description', models.TextField(help_text='حداکثر 170 کاراکتر', null=True, validators=[django.core.validators.MaxLengthValidator(170)], verbose_name='meta description (SEO)')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=portfolio.models.posts_thumb_path)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': '   Projects',
            },
        ),
    ]
