# Generated by Django 3.2.9 on 2022-01-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='language_field',
            field=models.CharField(blank=True, choices=[('persian', 'persian'), ('english', 'english')], max_length=256, null=True),
        ),
    ]
